name: Test Backend

on:
  # On every push to main, and pull request for merging to main, run this action.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'server'
    
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      # Build on Node 16
      - name: Build on Node ver. 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm build

      # Build on Node 18
      - name: Build on Node ver. 18
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm ci
      - run: npm build

  Test:
    runs-on: ubuntu-latest

    
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      # Test on Node 16
      - name: Build on Node ver. 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd server
      - run: npm ci
      - run: npm test

      # Test on Node 18
      - name: Build on Node ver. 18
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: cd server
      - run: npm ci
      - run: npm test


