name: Test Backend

on:
  # On every push to main, and pull request for merging to main, run this action.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v3

      # Build on Node 16
      - name: Setup Node ver. 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          pwd
          npm ci
          npm run build
        working-directory: ./server

  Test:
    runs-on: ubuntu-latest

    
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@v3


